<a href="https://colab.research.google.com/github/Greeshu-09/AISECT-AIML/blob/main/CKD_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
dataset = pd.read_csv('/content/kidney_disease.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [4]:
dataset = dataset.drop('id', axis=1)

In [5]:
dataset.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd

In [6]:
import numpy as np
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["age"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["age"])

#step 5 : round the value
dataset[["age"]] =np.round(imputed_df).astype(int)

In [7]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bp"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bp"])
dataset[["bp"]] =imputed_df

In [8]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sg"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sg"])
dataset[["sg"]]=imputed_df

In [9]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["al"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["al"])

# Round & clip 'al'
dataset[["al"]] = np.clip(np.round(imputed_df), 0, 5).astype(int)

In [10]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["su"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["su"])
dataset[["su"]]=imputed_df

In [11]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bu"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bu"])
dataset[["bu"]]=imputed_df

In [12]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bgr"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bgr"])
dataset[["bgr"]] =imputed_df

In [13]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sc"])
dataset[["sc"]]=imputed_df

In [14]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sod"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sod"])
dataset[["sod"]]=imputed_df

In [15]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pot"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pot"])

dataset[["pot"]] =imputed_df

In [16]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["hemo"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["hemo"])
dataset[["hemo"]] =imputed_df

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             400 non-null    int64
 1   bp              400 non-null    float64
 2   sg              400 non-null    float64
 3   al              400 non-null    int64
 4   su              400 non-null    float64
 5   rbc             248 non-null    object
 6   pc              335 non-null    object
 7   pcc             396 non-null    object
 8   ba              396 non-null    object
 9   bgr             400 non-null    float64
 10  bu              400 non-null    float64
 11  sc              400 non-null    float64
 12  sod             400 non-null    float64
 13  pot             400 non-null    float64
 14  hemo            400 non-null    float64
 15  pcv             330 non-null    object
 16  wc              295 non-null    object
 17  rc              270 non-null    object
 18  htn             398 non-null    object
 19  dm              398 non-null    object
 20  cad             398 non-null    object
 21  appet           399 non-null    object
 22  pe              399 non-null    object
 23  ane             399 non-null    object
 24  classification  400 non-null    object
dtypes: float64(9), int64(2), object(14)
memory usage: 78.3+ KB

In [18]:
dataset['rbc'].value_counts()

rbc
normal      201
abnormal     47
Name: count, dtype: int64

In [19]:
dataset[["rbc"]].isnull().sum()

rbc    152
dtype: int64

In [20]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['rbc'].mode()[0]
dataset['rbc'] = dataset['rbc'].fillna(rbc_mode)
display(dataset[['rbc']].isnull().sum())

rbc    0
dtype: int64

In [21]:
# Apply one-hot encoding to the 'rbc' column
dataset = pd.get_dummies(dataset, columns=['rbc'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal
0,48,80.0,1.020,1,0.0,normal,notpresent,notpresent,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,1
1,7,50.0,1.020,4,0.0,normal,notpresent,notpresent,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,1
2,62,80.0,1.010,2,3.0,normal,notpresent,notpresent,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1
3,48,70.0,1.005,4,0.0,abnormal,present,notpresent,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1
4,51,80.0,1.010,2,0.0,normal,notpresent,notpresent,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1

In [22]:
# Impute missing values in 'pc' with the mode
pc_mode = dataset['pc'].mode()[0]
dataset['pc'] = dataset['pc'].fillna(pc_mode)
display(dataset[['pc']].isnull().sum())

pc    0
dtype: int64

In [23]:
# Apply one-hot encoding to the 'pc' column
dataset = pd.get_dummies(dataset, columns=['pc'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal
0,48,80.0,1.020,1,0.0,notpresent,notpresent,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,1,1
1,7,50.0,1.020,4,0.0,notpresent,notpresent,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,1,1
2,62,80.0,1.010,2,3.0,notpresent,notpresent,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1,1
3,48,70.0,1.005,4,0.0,present,notpresent,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1,0
4,51,80.0,1.010,2,0.0,notpresent,notpresent,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1,1

In [24]:
dataset[["pcc"]].isnull().sum()

pcc    4
dtype: int64

In [25]:
# Apply one-hot encoding to the 'pc' column
dataset = pd.get_dummies(dataset, columns=['pcc'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present
0,48,80.0,1.020,1,0.0,notpresent,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,1,1,0
1,7,50.0,1.020,4,0.0,notpresent,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,1,1,0
2,62,80.0,1.010,2,3.0,notpresent,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1,1,0
3,48,70.0,1.005,4,0.0,notpresent,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1,0,1
4,51,80.0,1.010,2,0.0,notpresent,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1,1,0

In [26]:
dataset[['ba']].isnull().sum()

ba    4
dtype: int64

In [27]:
# Impute missing values in 'ba' with the mode
ba_mode = dataset['ba'].mode()[0]
dataset['ba'] = dataset['ba'].fillna(ba_mode)
display(dataset[['ba']].isnull().sum())

ba    0
dtype: int64

In [28]:
# Apply one-hot encoding to the 'pc' column
dataset = pd.get_dummies(dataset, columns=['ba'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present
0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,1,1,0,0
1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,1,1,0,0
2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1,1,0,0
3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1,0,1,0
4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1,1,0,0

In [29]:
dataset[["htn"]].value_counts()

htn
no     251
yes    147
Name: count, dtype: int64

In [30]:
dataset[['htn']].isnull().sum()

htn    2
dtype: int64

In [31]:
ba_mode = dataset['htn'].mode()[0]
dataset['htn'] = dataset['htn'].fillna(ba_mode)
display(dataset[['htn']].isnull().sum())

htn    0
dtype: int64

In [32]:
# Apply one-hot encoding to the 'pc' column
dataset = pd.get_dummies(dataset, columns=['htn'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes
0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44,7800,5.2,yes,no,good,no,no,ckd,1,1,0,0,1
1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38,6000,NaN,no,no,good,no,no,ckd,1,1,0,0,0
2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31,7500,NaN,yes,no,poor,no,yes,ckd,1,1,0,0,0
3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32,6700,3.9,no,no,poor,yes,yes,ckd,1,0,1,0,1
4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35,7300,4.6,no,no,good,no,no,ckd,1,1,0,0,0

In [33]:
# Display unique values in the 'pcv' column
display(dataset['pcv'].unique())

array(['44', '38', '31', '32', '35', '39', '36', '33', '29', '28', nan,
       '16', '24', '37', '30', '34', '40', '45', '27', '48', '\t?', '52',
       '14', '22', '18', '42', '17', '46', '23', '19', '25', '41', '26',
       '15', '21', '43', '20', '\t43', '47', '9', '49', '50', '53', '51',
       '54'], dtype=object)

Okay, I see the unique values in the 'pcv' column include '\t?' and '\t43', which are causing it to be treated as an object type. To prepare this column for numerical analysis, we should replace these problematic string values.

I will replace '\t?' and '\t43' with NaN and then convert the column to a numeric type. Any values that cannot be converted will also become NaN.

In [34]:
# Replace '\t?' and '\t43' with NaN in 'pcv' column
dataset['pcv'] = dataset['pcv'].replace({'\t?': np.nan, '\t43': np.nan})

# Convert the 'pcv' column to numeric, coercing errors to NaN
dataset['pcv'] = pd.to_numeric(dataset['pcv'], errors='coerce')

# Display the unique values and missing values after replacement and conversion
display(dataset['pcv'].unique())
display(dataset['pcv'].isnull().sum())

array([44., 38., 31., 32., 35., 39., 36., 33., 29., 28., nan, 16., 24.,
       37., 30., 34., 40., 45., 27., 48., 52., 14., 22., 18., 42., 17.,
       46., 23., 19., 25., 41., 26., 15., 21., 43., 20., 47.,  9., 49.,
       50., 53., 51., 54.])

np.int64(72)

In [35]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pcv"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pcv"])
dataset[["pcv"]] =imputed_df

In [36]:
# Display unique values in the 'wc' column
display(dataset['wc'].unique())

array(['7800', '6000', '7500', '6700', '7300', nan, '6900', '9600',
       '12100', '4500', '12200', '11000', '3800', '11400', '5300', '9200',
       '6200', '8300', '8400', '10300', '9800', '9100', '7900', '6400',
       '8600', '18900', '21600', '4300', '8500', '11300', '7200', '7700',
       '14600', '6300', '\t6200', '7100', '11800', '9400', '5500', '5800',
       '13200', '12500', '5600', '7000', '11900', '10400', '10700',
       '12700', '6800', '6500', '13600', '10200', '9000', '14900', '8200',
       '15200', '5000', '16300', '12400', '\t8400', '10500', '4200',
       '4700', '10900', '8100', '9500', '2200', '12800', '11200', '19100',
       '\t?', '12300', '16700', '2600', '26400', '8800', '7400', '4900',
       '8000', '12000', '15700', '4100', '5700', '11500', '5400', '10800',
       '9900', '5200', '5900', '9300', '9700', '5100', '6600'],
      dtype=object)

In [37]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer

# Replace problematic string values with NaN in 'wc' column
dataset['wc'] = dataset['wc'].replace({'\t6200': np.nan, '\t8400': np.nan, '\t?': np.nan})

# Convert the 'wc' column to numeric, coercing errors to NaN
dataset['wc'] = pd.to_numeric(dataset['wc'], errors='coerce')

# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["wc"]])

# Step 2: Apply KNN Imputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["wc"])
dataset[["wc"]] =imputed_df

display(dataset[['wc']].isnull().sum()) # Display null count to confirm imputation

wc    0
dtype: int64

In [38]:
# Display unique values in the 'dm' column
display(dataset['dm'].unique())

array(['yes', 'no', ' yes', '\tno', '\tyes', nan], dtype=object)

In [39]:
# Clean 'dm' column by removing leading/trailing whitespaces and '\t'
dataset['dm'] = dataset['dm'].str.strip().str.replace('\t', '', regex=False)

# Display unique values and missing values after cleaning
display(dataset['dm'].unique())
display(dataset['dm'].isnull().sum())

array(['yes', 'no', nan], dtype=object)

np.int64(2)

In [40]:
# Impute missing values in 'dm' with the mode
dm_mode = dataset['dm'].mode()[0]
dataset['dm'] = dataset['dm'].fillna(dm_mode)
display(dataset[['dm']].isnull().sum())

dm    0
dtype: int64

In [41]:
# Apply one-hot encoding to the 'pc' column
dataset = pd.get_dummies(dataset, columns=['dm'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes
0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.2,no,good,no,no,ckd,1,1,0,0,1,1
1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,NaN,no,good,no,no,ckd,1,1,0,0,0,0
2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,NaN,no,poor,no,yes,ckd,1,1,0,0,0,1
3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.9,no,poor,yes,yes,ckd,1,0,1,0,1,0
4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.6,no,good,no,no,ckd,1,1,0,0,0,0

In [42]:
# Display unique values in the 'rc' column
display(dataset['rc'].unique())

array(['5.2', nan, '3.9', '4.6', '4.4', '5', '4.0', '3.7', '3.8', '3.4',
       '2.6', '2.8', '4.3', '3.2', '3.6', '4', '4.1', '4.9', '2.5', '4.2',
       '4.5', '3.1', '4.7', '3.5', '6.0', '5.0', '2.1', '5.6', '2.3',
       '2.9', '2.7', '8.0', '3.3', '3.0', '3', '2.4', '4.8', '\t?', '5.4',
       '6.1', '6.2', '6.3', '5.1', '5.8', '5.5', '5.3', '6.4', '5.7',
       '5.9', '6.5'], dtype=object)

In [43]:
# Replace '\t?' with NaN in 'rc' column
dataset['rc'] = dataset['rc'].replace({'\t?': np.nan})

# Convert the 'rc' column to numeric, coercing errors to NaN
dataset['rc'] = pd.to_numeric(dataset['rc'], errors='coerce')

# Display the unique values and missing values after replacement and conversion
display(dataset['rc'].unique())
display(dataset['rc'].isnull().sum())

array([5.2, nan, 3.9, 4.6, 4.4, 5. , 4. , 3.7, 3.8, 3.4, 2.6, 2.8, 4.3,
       3.2, 3.6, 4.1, 4.9, 2.5, 4.2, 4.5, 3.1, 4.7, 3.5, 6. , 2.1, 5.6,
       2.3, 2.9, 2.7, 8. , 3.3, 3. , 2.4, 4.8, 5.4, 6.1, 6.2, 6.3, 5.1,
       5.8, 5.5, 5.3, 6.4, 5.7, 5.9, 6.5])

np.int64(131)

In [44]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["rc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["rc"])
dataset[["rc"]] =imputed_df

In [45]:
# Display unique values in the 'cad' column
display(dataset['cad'].unique())

array(['no', 'yes', '\tno', nan], dtype=object)

In [46]:
# Clean 'cad' column by removing '\t' and leading/trailing whitespaces
dataset['cad'] = dataset['cad'].str.strip().str.replace('\t', '', regex=False)

# Display unique values and missing values after cleaning
display(dataset['cad'].unique())
display(dataset['cad'].isnull().sum())

array(['no', 'yes', nan], dtype=object)

np.int64(2)

In [47]:
# Impute missing values in 'dm' with the mode
dm_mode = dataset['cad'].mode()[0]
dataset['cad'] = dataset['cad'].fillna(dm_mode)
display(dataset[['cad']].isnull().sum())

cad    0
dtype: int64

In [48]:
# Apply one-hot encoding to the 'cad' column
dataset = pd.get_dummies(dataset, columns=['cad'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes
0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,good,no,no,ckd,1,1,0,0,1,1,0
1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,good,no,no,ckd,1,1,0,0,0,0,0
2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,poor,no,yes,ckd,1,1,0,0,0,1,0
3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,poor,yes,yes,ckd,1,0,1,0,1,0,0
4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,good,no,no,ckd,1,1,0,0,0,0,0

In [49]:
# Display unique values in the 'appet' column
display(dataset['appet'].unique())

array(['good', 'poor', nan], dtype=object)

In [50]:
# Impute missing values in 'appet' with the mode
appet_mode = dataset['appet'].mode()[0]
dataset['appet'] = dataset['appet'].fillna(appet_mode)
display(dataset[['appet']].isnull().sum())

appet    0
dtype: int64

In [51]:
# Apply one-hot encoding to the 'appet' column
dataset = pd.get_dummies(dataset, columns=['appet'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor
0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,no,no,ckd,1,1,0,0,1,1,0,0
1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,ckd,1,1,0,0,0,0,0,0
2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,yes,ckd,1,1,0,0,0,1,0,1
3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,yes,ckd,1,0,1,0,1,0,0,1
4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,ckd,1,1,0,0,0,0,0,0

In [52]:
# Display unique values in the 'pe' column
display(dataset['pe'].unique())

array(['no', 'yes', nan], dtype=object)

In [53]:
# Impute missing values in 'pe' with the mode
pe_mode = dataset['pe'].mode()[0]
dataset['pe'] = dataset['pe'].fillna(pe_mode)
display(dataset[['pe']].isnull().sum())

pe    0
dtype: int64

In [54]:
# Apply one-hot encoding to the 'appet' column
dataset = pd.get_dummies(dataset, columns=['pe'], drop_first=True,dummy_na=False,dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes
0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,no,ckd,1,1,0,0,1,1,0,0,0
1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,ckd,1,1,0,0,0,0,0,0,0
2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,yes,ckd,1,1,0,0,0,1,0,1,0
3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,ckd,1,0,1,0,1,0,0,1,1
4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,ckd,1,1,0,0,0,0,0,0,0

In [55]:
# Display unique values in the 'ane' column
display(dataset['ane'].unique())

array(['no', 'yes', nan], dtype=object)

In [56]:
# Impute missing values in 'ane' with the mode
ane_mode = dataset['ane'].mode()[0]
dataset['ane'] = dataset['ane'].fillna(ane_mode)
display(dataset[['ane']].isnull().sum())

ane    0
dtype: int64

In [57]:
# Apply one-hot encoding to the 'ane' column
dataset = pd.get_dummies(dataset, columns=['ane'], drop_first=True, dummy_na=False, dtype=int)

# Display the first few rows to show the result
display(dataset.head())

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,ckd,1,1,0,0,1,1,0,0,0,0
1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,ckd,1,1,0,0,0,0,0,0,0,0
2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,ckd,1,1,0,0,0,1,0,1,0,1
3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,ckd,1,0,1,0,1,0,0,1,1,1
4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,ckd,1,1,0,0,0,0,0,0,0,0

In [58]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             400 non-null    int64
 1   bp              400 non-null    float64
 2   sg              400 non-null    float64
 3   al              400 non-null    int64
 4   su              400 non-null    float64
 5   bgr             400 non-null    float64
 6   bu              400 non-null    float64
 7   sc              400 non-null    float64
 8   sod             400 non-null    float64
 9   pot             400 non-null    float64
 10  hemo            400 non-null    float64
 11  pcv             400 non-null    float64
 12  wc              400 non-null    float64
 13  rc              400 non-null    float64
 14  classification  400 non-null    object
 15  rbc_normal      400 non-null    int64
 16  pc_normal       400 non-null    int64
 17  pcc_present     400 non-null    int64
 18  ba_present      400 non-null    int64
 19  htn_yes         400 non-null    int64
 20  dm_yes          400 non-null    int64
 21  cad_yes         400 non-null    int64
 22  appet_poor      400 non-null    int64
 23  pe_yes          400 non-null    int64
 24  ane_yes         400 non-null    int64
dtypes: float64(12), int64(12), object(1)
memory usage: 78.3+ KB

In [59]:
# Display the value counts of the encoded 'classification' column
display(dataset['classification'].value_counts())

classification
ckd       248
notckd    150
ckd\t       2
Name: count, dtype: int64

In [60]:
dataset['classification'] = dataset['classification'].replace('ckd\t', 'ckd')

In [61]:
# Display unique values in the 'pe' column
display(dataset['classification'].unique())

array(['ckd', 'notckd'], dtype=object)

In [62]:
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
import pickle
import matplotlib.pyplot as plt

In [63]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo',
       'pcv', 'wc', 'rc', 'classification', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_poor', 'pe_yes', 'ane_yes'],
      dtype='object')

In [64]:
indep_X=dataset[['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot',
       'hemo', 'pcv', 'wc', 'rc', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'appet_poor', 'pe_yes',
       'ane_yes', 'dm_yes', 'cad_yes']]

In [65]:
dep_Y=dataset[['classification']]

*Recursive Feature Elimination*

The scaling you did during KNN imputation was applied to individual columns or small groups of columns to help the imputer. However, for RFE, you typically want to scale all your independent variables (indep_X) together after all the imputation and preprocessing steps are complete and after you've split your data into training and testing sets.

Scaling the entire feature set before applying RFE ensures that features with different ranges of values don't unfairly influence the feature selection process based on their magnitude. So, yes, you should still apply StandardScaler to your training and testing sets (using a scaler fitted only on the training data) before using RFE.

In [66]:
def split_scalar(X,Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)

#creating function from classification metrics as a performance metric
def classification_metrics(classifier, X_test, y_test):
    # Predictions
    y_pred = classifier.predict(X_test)

    # Import metrics
    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')  # use 'binary' for binary problems
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    # Optional: classification report
    report = classification_report(y_test, y_pred)

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'confusion_matrix': cm,
        'classification_report': report
    }

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

def train_and_evaluate_logistic_regression(X, y):
    """
    Trains a Logistic Regression classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

    # Initialize and train the Logistic Regression classifier
    lr_classifier = LogisticRegression(random_state=42, solver='liblinear') # Added solver for clarity
    lr_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(lr_classifier, X_test, y_test)

    return metrics

In [68]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

def train_and_evaluate_random_forest(X, y):
    """
    Trains a Random Forest classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

    # Initialize and train the Random Forest classifier
    rf_classifier = RandomForestClassifier(random_state=42)
    rf_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(rf_classifier, X_test, y_test)

    return metrics

In [69]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

def train_and_evaluate_decision_tree(X, y):
    """
    Trains a Decision Tree classifier, evaluates its performance, and returns metrics.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

    # Initialize and train the Decision Tree classifier
    dt_classifier = DecisionTreeClassifier(random_state=42)
    dt_classifier.fit(X_train, y_train)

    # Evaluate the classifier using the existing classification_metrics function
    metrics = classification_metrics(dt_classifier, X_test, y_test)

    return metrics

In [70]:
#this function automates the process of applying RFE with different classifiers, training those classifiers on the RFE-selected features, and evaluating their performance.
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split # Ensure train_test_split is imported here

def evaluate_models_with_rfe(X, y, n):
    """
    Applies RFE with various classifiers to select top features and evaluates models.

    Args:
        X: Features (DataFrame).
        y: Target (Series or DataFrame).
        n: The number of features to select.

    Returns:
        A dictionary where keys are model names and values are a dictionary containing their performance metrics and selected features.
    """
    results = {}

    # Define classifiers to use with RFE
    classifiers = {
        "Decision Tree": DecisionTreeClassifier(random_state=42),
        "Logistic Regression": LogisticRegression(random_state=42, solver='liblinear'),
        "Random Forest": RandomForestClassifier(random_state=42),
    }

    # Define classifiers to evaluate without RFE (if needed, or handle separately)
    # For now, focusing on RFE compatible models as per the function's purpose

    for name, classifier in classifiers.items():
        print(f"Evaluating {name} with RFE...")

        # Initialize RFE
        rfe = RFE(estimator=classifier, n_features_to_select=n)

        # Fit RFE
        rfe.fit(X, y)

        # Get the selected features
        selected_features = X.columns[rfe.support_].tolist()

        # Split data into training and testing sets using selected features
        X_selected = X[selected_features]
        X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.3, random_state=0)


        # Train the classifier on the selected features
        model = classifier
        model.fit(X_train, y_train)

        # Evaluate the classifier
        metrics = classification_metrics(model, X_test, y_test)
        results[name] = {'metrics': metrics, 'selected_features': selected_features}
        print(f"{name} Evaluation Complete.\n")

    return results

In [71]:
n_features = 5

# Call the function with your data
rfe_results = evaluate_models_with_rfe(indep_X, dep_Y.values.ravel(), n_features)

# Print the results for each model in the requested format
for model_name, result_data in rfe_results.items():
    print(f"Model: {model_name}")
    print("Selected Columns:", result_data['selected_features'])
    # Print classification metrics
    print(f"Accuracy: {result_data['metrics']['accuracy']:.4f}")
    print(f"Precision: {result_data['metrics']['precision']:.4f}")
    print(f"Recall: {result_data['metrics']['recall']:.4f}")
    print(f"F1-Score: {result_data['metrics']['f1_score']:.4f}")
    print(f"Confusion Matrix:\n{result_data['metrics']['confusion_matrix']}\n")

Evaluating Decision Tree with RFE...
Decision Tree Evaluation Complete.

Evaluating Logistic Regression with RFE...
Logistic Regression Evaluation Complete.

Evaluating Random Forest with RFE...
Random Forest Evaluation Complete.

Model: Decision Tree
Selected Columns: ['sg', 'bu', 'hemo', 'rc', 'htn_yes']
Accuracy: 0.9583
Precision: 0.9583
Recall: 0.9583
F1-Score: 0.9583
Confusion Matrix:
[[70  2]
 [ 3 45]]

Model: Logistic Regression
Selected Columns: ['al', 'htn_yes', 'appet_poor', 'pe_yes', 'dm_yes']
Accuracy: 0.9250
Precision: 0.9254
Recall: 0.9250
F1-Score: 0.9251
Confusion Matrix:
[[67  5]
 [ 4 44]]

Model: Random Forest
Selected Columns: ['sg', 'al', 'sc', 'hemo', 'pcv']
Accuracy: 0.9750
Precision: 0.9760
Recall: 0.9750
F1-Score: 0.9749
Confusion Matrix:
[[72  0]
 [ 3 45]]

In [72]:
from sklearn.ensemble import RandomForestClassifier

In [73]:
from sklearn.ensemble import RandomForestClassifier

# Get the features selected by RFE for the Random Forest model
rf_selected_features = rfe_results['Random Forest']['selected_features']
X_selected_rf = indep_X[rf_selected_features]
y = dep_Y.values.ravel() # Ensure y is a 1D array

# Split data into training and testing sets using the selected features
X_train, X_test, y_train, y_test = train_test_split(X_selected_rf, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# You can now evaluate the model using classification_metrics if needed
# rf_metrics = classification_metrics(rf, X_test, y_test)
# print(rf_metrics)

In [74]:
# Evaluate the trained Random Forest model
rf_metrics = classification_metrics(rf, X_test, y_test)

# Print the evaluation metrics
print("Random Forest Model Evaluation Metrics:")
print(f"Accuracy: {rf_metrics['accuracy']:.4f}")
print(f"Precision: {rf_metrics['precision']:.4f}")
print(f"Recall: {rf_metrics['recall']:.4f}")
print(f"F1-Score: {rf_metrics['f1_score']:.4f}")
print(f"Confusion Matrix:\n{rf_metrics['confusion_matrix']}\n")
print(f"Classification Report:\n{rf_metrics['classification_report']}")

Random Forest Model Evaluation Metrics:
Accuracy: 0.9875
Precision: 0.9879
Recall: 0.9875
F1-Score: 0.9875
Confusion Matrix:
[[51  1]
 [ 0 28]]

Classification Report:
              precision    recall  f1-score   support

         ckd       1.00      0.98      0.99        52
      notckd       0.97      1.00      0.98        28

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [75]:
import pickle
filename = "RandomForestClassification.sav"
pickle.dump(rf,open(filename,"wb"))
load_model=pickle.load(open(filename,"rb"))

In [76]:
load_model=pickle.load(open("/content/RandomForestClassification.sav","rb"))

In [77]:

#testing the model
result=load_model.predict([[1.020,1,1.2,1.4,44.0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [78]:
result

array(['ckd'], dtype=object)